### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by qpmnguyen** [difuse-dartmouth/DIFUSE_2020_EddyCovariance#1]
Some checklist items thought up as reminder for code: 

- [ ] Add functionality to get add density to bivariate plots. 
- [ ] Modularize Shiny app
- [x] Make plots interactive using plotly
- [x]  Add button to render graph instead of letting it render automatically  
- [x]  Zoom in and out of different time sections  
- [x]  Average within second and give option to smooth (moving average) with choice of moving average frames  
- [ ]  Work on double axis plot to 
- [ ]  Make things less funky on the sliders
